
package view;

import controller.PlayerController;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Eduardo
 * 
 * Player JFrame
 */
public class Player extends javax.swing.JFrame {

    private PlayerController app;
    private Register newUser;

    /**
     * Creates new form Player
     */
    public Player() {
        initComponents();
        app = new PlayerController();
        newUser = new Register();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlayPause = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        spPlaylists = new javax.swing.JScrollPane();
        lbPlaylists = new javax.swing.JList<>();
        spSongs = new javax.swing.JScrollPane();
        lbSongs = new javax.swing.JList<>();
        lblUsersName = new javax.swing.JLabel();
        lblPlaylists = new javax.swing.JLabel();
        lblSongs = new javax.swing.JLabel();
        btnNewPlaylist = new javax.swing.JButton();
        btnAddFile = new javax.swing.JButton();
        btnAddDirectory = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnRepeat = new javax.swing.JButton();
        mnuBar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuExit = new javax.swing.JMenuItem();
        mnuUsers = new javax.swing.JMenu();
        mnuNewUser = new javax.swing.JMenuItem();
        mnuViewUsers = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Music Player");
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setName("Player"); // NOI18N
        setResizable(false);

        btnPlayPause.setText("P");
        btnPlayPause.setPreferredSize(new java.awt.Dimension(60, 60));
        btnPlayPause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPlayPauseMouseReleased(evt);
            }
        });

        btnNext.setText("N");
        btnNext.setPreferredSize(new java.awt.Dimension(45, 45));
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNextMouseReleased(evt);
            }
        });

        btnPrevious.setText("PR");
        btnPrevious.setPreferredSize(new java.awt.Dimension(45, 45));
        btnPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPreviousMouseReleased(evt);
            }
        });

        spPlaylists.setViewportView(lbPlaylists);

        spSongs.setViewportView(lbSongs);

        lblUsersName.setText("User's type");

        lblPlaylists.setText("Playlists:");

        lblSongs.setText("Songs:");

        btnNewPlaylist.setText("New Playlist");

        btnAddFile.setText("Add File");
        btnAddFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddFileMouseReleased(evt);
            }
        });
        btnAddFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFileActionPerformed(evt);
            }
        });

        btnAddDirectory.setText("Add Directory");

        btnStop.setText("S");
        btnStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnStopMouseReleased(evt);
            }
        });

        btnRepeat.setText("R");

        mnuFile.setText("File");

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuExit);

        mnuBar.add(mnuFile);

        mnuUsers.setText("Users");

        mnuNewUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuNewUser.setText("New user...");
        mnuNewUser.setToolTipText("");
        mnuNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNewUserActionPerformed(evt);
            }
        });
        mnuUsers.add(mnuNewUser);

        mnuViewUsers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mnuViewUsers.setText("View users");
        mnuViewUsers.setToolTipText("");
        mnuUsers.add(mnuViewUsers);

        mnuBar.add(mnuUsers);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlaylists)
                            .addComponent(spPlaylists, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblUsersName)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRepeat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayPause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStop))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblSongs)
                        .addComponent(spSongs, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNewPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnAddFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddDirectory, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblSongs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsersName)
                        .addGap(30, 30, 30)
                        .addComponent(lblPlaylists)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spPlaylists))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(spSongs, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAddFile)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnAddDirectory)
                            .addGap(50, 50, 50)
                            .addComponent(btnNewPlaylist))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlayPause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStop)
                    .addComponent(btnRepeat))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void btnStopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStopMouseReleased
        app.Stop();
        btnPlayPause.setText("P");
    }//GEN-LAST:event_btnStopMouseReleased

    private void btnPlayPauseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayPauseMouseReleased
        app.PlayPause(app.getSongLocationList().get(lbSongs.getSelectedIndex()));
        if (app.isPlaying()) {
            btnPlayPause.setText("PA");
        } else {
            btnPlayPause.setText("P");
        }
    }//GEN-LAST:event_btnPlayPauseMouseReleased

    private void btnAddFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddFileActionPerformed

    private void btnAddFileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddFileMouseReleased
        //String[] list = {app.addFile()};
        app.addFile();
        String songs[] = app.getSongNameList().toArray(new String[app.getSongNameList().size()]);
        lbSongs.setListData(songs);
    }//GEN-LAST:event_btnAddFileMouseReleased

    private void btnNextMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseReleased
        if (lbSongs.getSelectedIndex() + 1 < app.getSongLocationList().size()) {
            lbSongs.setSelectedIndex(lbSongs.getSelectedIndex() + 1);
        } else {
            lbSongs.setSelectedIndex(0);
        }
        app.Stop();
        app.PlayPause(app.getSongLocationList().get(lbSongs.getSelectedIndex()));
    }//GEN-LAST:event_btnNextMouseReleased

    private void btnPreviousMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreviousMouseReleased
        if (lbSongs.getSelectedIndex() - 1 >= 0) {
            lbSongs.setSelectedIndex(lbSongs.getSelectedIndex() - 1);
        }
        else{
            lbSongs.setSelectedIndex(app.getSongLocationList().size() - 1);
        }
        app.Stop();
        app.PlayPause(app.getSongLocationList().get(lbSongs.getSelectedIndex()));
    }//GEN-LAST:event_btnPreviousMouseReleased

    private void mnuNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNewUserActionPerformed
        newUser.setVisible(true);
    }//GEN-LAST:event_mnuNewUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDirectory;
    private javax.swing.JButton btnAddFile;
    private javax.swing.JButton btnNewPlaylist;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPlayPause;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnRepeat;
    private javax.swing.JButton btnStop;
    private javax.swing.JList<String> lbPlaylists;
    private javax.swing.JList<String> lbSongs;
    private javax.swing.JLabel lblPlaylists;
    private javax.swing.JLabel lblSongs;
    private javax.swing.JLabel lblUsersName;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuNewUser;
    private javax.swing.JMenu mnuUsers;
    private javax.swing.JMenuItem mnuViewUsers;
    private javax.swing.JScrollPane spPlaylists;
    private javax.swing.JScrollPane spSongs;
    // End of variables declaration//GEN-END:variables
}
